import { isLang, type Lang, t } from "../../../lib/i18n";

type Section = { title: string; paragraphs: string[] };
type TermsContent = { sections: Section[]; lastUpdatedLabel: string; backLabel: string };

const TERMS_BY_LANG: Record<Lang, TermsContent> = {
  en: {
    sections: [
      {
        title: "1. General Information",
        paragraphs: [
          "These terms govern the use of the Winqo platform for generating window quotations.",
          "Owner: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Poland.",
        ],
      },
      {
        title: "2. Definitions",
        paragraphs: [
          "Platform – the Winqo SaaS system.",
          "User – any person or entity using the Platform.",
          "Account – an individual user account in the Platform.",
          "Subscription – paid access to Platform features.",
          "Quotation – a document generated by the Platform.",
        ],
      },
      {
        title: "3. Conditions of Use",
        paragraphs: [
          "Use requires registration and acceptance of these terms.",
          "Users must provide accurate data during registration.",
          "Login credentials must not be shared with third parties.",
          "Use the Platform in compliance with law and good practice.",
        ],
      },
      {
        title: "4. Plans and Payments",
        paragraphs: [
          "Multiple subscription plans are available with specific limits and features.",
          "Fees are charged in advance monthly or yearly.",
          "Plan changes can be made anytime and apply from the next billing period.",
          "Missing payments may block access to the Platform.",
          "Payments are non-refundable unless required by law.",
        ],
      },
      {
        title: "5. Personal Data",
        paragraphs: [
          "Data controller: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Poland.",
          "Data are processed under GDPR to deliver the service.",
          "Users can access, rectify, erase, and port their data.",
          "Data are not shared with third parties without consent, except payment processors.",
        ],
      },
      {
        title: "6. Liability",
        paragraphs: [
          "The Platform is provided \"as is\" without guaranteed uptime.",
          "The owner is not liable for damages from use or inability to use the Platform.",
          "Users are responsible for content of generated quotations.",
          "Maintenance windows may occur.",
        ],
      },
      {
        title: "7. Intellectual Property",
        paragraphs: [
          "All rights to the Platform, including code and documentation, belong to the owner.",
          "Users receive a non-exclusive license within their subscription.",
          "Copying or distributing the Platform without consent is forbidden.",
        ],
      },
      {
        title: "8. Termination",
        paragraphs: [
          "Users may cancel a subscription at any time.",
          "The owner may terminate with 30 days' notice or immediately for breach.",
          "User data may be deleted 30 days after termination.",
        ],
      },
      {
        title: "9. Final Provisions",
        paragraphs: [
          "The owner may update these terms; changes take effect 14 days after publication.",
          "Polish law governs matters not covered here.",
          "Disputes are resolved by the court competent for the owner's seat.",
          "Contact: via the form available in the Platform.",
        ],
      },
    ],
    lastUpdatedLabel: "Last updated",
    backLabel: "Back to home",
  },
  pl: {
    sections: [
      {
        title: "1. Informacje ogólne",
        paragraphs: [
          "Niniejszy regulamin określa zasady korzystania z platformy Winqo do generowania wycen okien.",
          "Właściciel: Camillo Kamil Kwapich, ul. Świerkowa 33b, 46-100 Namysłów, Polska.",
        ],
      },
      {
        title: "2. Definicje",
        paragraphs: [
          "Platforma – system SaaS Winqo.",
          "Użytkownik – osoba lub podmiot korzystający z Platformy.",
          "Konto – indywidualne konto Użytkownika w Platformie.",
          "Subskrypcja – płatny dostęp do funkcjonalności Platformy.",
          "Wycena – dokument generowany przez Platformę.",
        ],
      },
      {
        title: "3. Warunki korzystania",
        paragraphs: [
          "Korzystanie wymaga rejestracji i akceptacji Regulaminu.",
          "Dane rejestracyjne muszą być prawdziwe.",
          "Dane logowania nie mogą być udostępniane osobom trzecim.",
          "Korzystanie musi być zgodne z prawem i dobrymi obyczajami.",
        ],
      },
      {
        title: "4. Plany i płatności",
        paragraphs: [
          "Dostępne są różne plany z określonymi limitami i funkcjami.",
          "Opłaty pobierane są z góry w cyklu miesięcznym lub rocznym.",
          "Zmianę planu można wprowadzić w dowolnym momencie; obowiązuje od następnego okresu.",
          "Brak płatności może zablokować dostęp do Platformy.",
          "Płatności są nierefundowalne, chyba że prawo stanowi inaczej.",
        ],
      },
      {
        title: "5. Ochrona danych",
        paragraphs: [
          "Administrator danych: Camillo Kamil Kwapich, ul. Świerkowa 33b, 46-100 Namysłów, Polska.",
          "Dane przetwarzane są zgodnie z RODO w celu świadczenia usług.",
          "Użytkownik ma prawo dostępu, sprostowania, usunięcia i przenoszenia danych.",
          "Dane nie są udostępniane podmiotom trzecim bez zgody, poza operatorami płatności.",
        ],
      },
      {
        title: "6. Odpowiedzialność",
        paragraphs: [
          "Platforma jest świadczona w modelu \"as is\" bez gwarancji dostępności.",
          "Właściciel nie odpowiada za szkody wynikłe z korzystania lub braku dostępu.",
          "Użytkownik odpowiada za treść generowanych wycen.",
          "Możliwe są przerwy techniczne i konserwacje.",
        ],
      },
      {
        title: "7. Własność intelektualna",
        paragraphs: [
          "Wszelkie prawa do Platformy, w tym kodu i dokumentacji, należą do Właściciela.",
          "Użytkownik otrzymuje niewyłączną licencję w ramach subskrypcji.",
          "Kopiowanie i rozpowszechnianie bez zgody jest zabronione.",
        ],
      },
      {
        title: "8. Rozwiązanie umowy",
        paragraphs: [
          "Użytkownik może zakończyć subskrypcję w dowolnym momencie.",
          "Właściciel może wypowiedzieć umowę z 30-dniowym terminem lub natychmiast przy naruszeniu.",
          "Dane mogą zostać usunięte po 30 dniach od zakończenia umowy.",
        ],
      },
      {
        title: "9. Postanowienia końcowe",
        paragraphs: [
          "Regulamin może być aktualizowany; zmiany obowiązują po 14 dniach od publikacji.",
          "W sprawach nieuregulowanych stosuje się prawo polskie.",
          "Spory rozstrzyga sąd właściwy dla siedziby Właściciela.",
          "Kontakt: formularz dostępny w Platformie.",
        ],
      },
    ],
    lastUpdatedLabel: "Ostatnia aktualizacja",
    backLabel: "Powrót do strony głównej",
  },
  de: {
    sections: [
      { title: "1. Allgemeine Informationen", paragraphs: [
        "Diese Bedingungen regeln die Nutzung der Winqo-Plattform zur Erstellung von Fensterangeboten.",
        "Inhaber: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Polen.",
      ]},
      { title: "2. Definitionen", paragraphs: [
        "Plattform – das Winqo-SaaS-System.",
        "Nutzer – jede Person oder Organisation, die die Plattform nutzt.",
        "Konto – individuelles Nutzerkonto in der Plattform.",
        "Abonnement – kostenpflichtiger Zugang zu Funktionen.",
        "Angebot – von der Plattform generiertes Dokument.",
      ]},
      { title: "3. Nutzungsbedingungen", paragraphs: [
        "Nutzung erfordert Registrierung und Zustimmung zu diesen Bedingungen.",
        "Registrierungsdaten müssen korrekt sein.",
        "Zugangsdaten dürfen nicht an Dritte weitergegeben werden.",
        "Die Plattform ist gesetzes- und zweckkonform zu verwenden.",
      ]},
      { title: "4. Pläne und Zahlungen", paragraphs: [
        "Es gibt mehrere Abonnements mit bestimmten Limits und Funktionen.",
        "Gebühren werden im Voraus monatlich oder jährlich berechnet.",
        "Planwechsel sind jederzeit möglich und gelten ab der nächsten Abrechnungsperiode.",
        "Ausbleibende Zahlungen können den Zugang sperren.",
        "Zahlungen sind nicht erstattungsfähig, sofern gesetzlich nichts anderes vorgeschrieben ist.",
      ]},
      { title: "5. Personenbezogene Daten", paragraphs: [
        "Datenverantwortlicher: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Polen.",
        "Daten werden gemäß DSGVO zur Dienstleistung verarbeitet.",
        "Nutzer können Daten einsehen, berichtigen, löschen und übertragen.",
        "Daten werden ohne Zustimmung nicht an Dritte weitergegeben, außer an Zahlungsanbieter.",
      ]},
      { title: "6. Haftung", paragraphs: [
        "Die Plattform wird \"as is\" bereitgestellt, ohne Verfügbarkeitsgarantie.",
        "Der Inhaber haftet nicht für Schäden aus Nutzung oder Nichtnutzung.",
        "Nutzer tragen Verantwortung für Inhalte ihrer Angebote.",
        "Wartungsfenster sind möglich.",
      ]},
      { title: "7. Geistiges Eigentum", paragraphs: [
        "Alle Rechte an Plattform, Code und Dokumentation liegen beim Inhaber.",
        "Nutzer erhalten eine nicht-exklusive Lizenz im Rahmen ihres Abos.",
        "Kopieren oder Verbreiten ohne Zustimmung ist untersagt.",
      ]},
      { title: "8. Kündigung", paragraphs: [
        "Nutzer können ein Abo jederzeit kündigen.",
        "Der Inhaber kann mit 30 Tagen Frist oder sofort bei Verstoß kündigen.",
        "Nutzerdaten können 30 Tage nach Beendigung gelöscht werden.",
      ]},
      { title: "9. Schlussbestimmungen", paragraphs: [
        "Der Inhaber kann Bedingungen aktualisieren; Änderungen gelten 14 Tage nach Veröffentlichung.",
        "Soweit nicht geregelt, gilt polnisches Recht.",
        "Streitigkeiten entscheidet das für den Sitz des Inhabers zuständige Gericht.",
        "Kontakt: Formular in der Plattform.",
      ]},
    ],
    lastUpdatedLabel: "Letzte Aktualisierung",
    backLabel: "Zur Startseite",
  },
  es: {
    sections: [
      { title: "1. Información general", paragraphs: [
        "Estos términos rigen el uso de la plataforma Winqo para generar cotizaciones de ventanas.",
        "Propietario: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Polonia.",
      ]},
      { title: "2. Definiciones", paragraphs: [
        "Plataforma – el sistema SaaS Winqo.",
        "Usuario – cualquier persona o entidad que use la Plataforma.",
        "Cuenta – cuenta individual del Usuario en la Plataforma.",
        "Suscripción – acceso de pago a funciones.",
        "Cotización – documento generado por la Plataforma.",
      ]},
      { title: "3. Condiciones de uso", paragraphs: [
        "El uso requiere registro y aceptación de estos términos.",
        "Los datos de registro deben ser correctos.",
        "Las credenciales no deben compartirse con terceros.",
        "El uso debe cumplir la ley y las buenas prácticas.",
      ]},
      { title: "4. Planes y pagos", paragraphs: [
        "Hay varios planes con límites y funciones definidos.",
        "Las tarifas se cobran por adelantado mensual o anualmente.",
        "Los cambios de plan pueden hacerse en cualquier momento y aplican al siguiente período.",
        "La falta de pago puede bloquear el acceso.",
        "Los pagos no son reembolsables salvo exigencia legal.",
      ]},
      { title: "5. Datos personales", paragraphs: [
        "Responsable: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Polonia.",
        "Los datos se procesan según GDPR para prestar el servicio.",
        "El usuario puede acceder, rectificar, borrar y portar sus datos.",
        "No se comparten datos con terceros sin consentimiento, salvo procesadores de pago.",
      ]},
      { title: "6. Responsabilidad", paragraphs: [
        "La plataforma se ofrece \"tal cual\" sin garantía de disponibilidad.",
        "El propietario no es responsable por daños derivados del uso o la imposibilidad de uso.",
        "El usuario responde por el contenido de las cotizaciones generadas.",
        "Pueden producirse mantenimientos.",
      ]},
      { title: "7. Propiedad intelectual", paragraphs: [
        "Todos los derechos de la Plataforma, código y documentación pertenecen al propietario.",
        "El usuario recibe una licencia no exclusiva dentro de su suscripción.",
        "Está prohibido copiar o distribuir sin consentimiento.",
      ]},
      { title: "8. Terminación", paragraphs: [
        "El usuario puede cancelar la suscripción en cualquier momento.",
        "El propietario puede rescindir con 30 días de aviso o de inmediato por incumplimiento.",
        "Los datos del usuario pueden eliminarse 30 días después de la terminación.",
      ]},
      { title: "9. Disposiciones finales", paragraphs: [
        "El propietario puede actualizar estos términos; entran en vigor 14 días tras su publicación.",
        "Se aplica la ley polaca en lo no regulado.",
        "Los conflictos se resuelven ante el tribunal competente del domicilio del propietario.",
        "Contacto: formulario en la Plataforma.",
      ]},
    ],
    lastUpdatedLabel: "Última actualización",
    backLabel: "Volver al inicio",
  },
  it: {
    sections: [
      { title: "1. Informazioni generali", paragraphs: [
        "Questi termini regolano l'uso della piattaforma Winqo per creare preventivi di finestre.",
        "Proprietario: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Polonia.",
      ]},
      { title: "2. Definizioni", paragraphs: [
        "Piattaforma – il sistema SaaS Winqo.",
        "Utente – persona o ente che usa la Piattaforma.",
        "Account – account individuale dell'Utente.",
        "Abbonamento – accesso a pagamento alle funzionalità.",
        "Preventivo – documento generato dalla Piattaforma.",
      ]},
      { title: "3. Condizioni d'uso", paragraphs: [
        "L'uso richiede registrazione e accettazione dei termini.",
        "I dati di registrazione devono essere corretti.",
        "Le credenziali non vanno condivise con terzi.",
        "L'uso deve rispettare la legge e le buone pratiche.",
      ]},
      { title: "4. Piani e pagamenti", paragraphs: [
        "Sono disponibili vari piani con limiti e funzioni definiti.",
        "Le tariffe si pagano anticipatamente su base mensile o annuale.",
        "I cambi piano sono possibili in ogni momento e valgono dal periodo successivo.",
        "La mancata pagamento può bloccare l'accesso.",
        "I pagamenti non sono rimborsabili salvo obbligo di legge.",
      ]},
      { title: "5. Dati personali", paragraphs: [
        "Titolare: Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Polonia.",
        "I dati sono trattati secondo il GDPR per erogare il servizio.",
        "L'utente può accedere, rettificare, cancellare e portare i propri dati.",
        "I dati non sono condivisi con terzi senza consenso, salvo i processori di pagamento.",
      ]},
      { title: "6. Responsabilità", paragraphs: [
        "La Piattaforma è fornita \"così com'è\" senza garanzia di disponibilità.",
        "Il proprietario non è responsabile di danni derivanti dall'uso o dal mancato uso.",
        "L'utente è responsabile del contenuto dei preventivi generati.",
        "Possono verificarsi finestre di manutenzione.",
      ]},
      { title: "7. Proprietà intellettuale", paragraphs: [
        "Tutti i diritti sulla Piattaforma, codice e documentazione appartengono al proprietario.",
        "L'utente riceve una licenza non esclusiva nell'ambito dell'abbonamento.",
        "È vietato copiare o distribuire senza consenso.",
      ]},
      { title: "8. Recesso", paragraphs: [
        "L'utente può annullare l'abbonamento in qualsiasi momento.",
        "Il proprietario può recedere con 30 giorni di preavviso o subito in caso di violazione.",
        "I dati possono essere eliminati dopo 30 giorni dalla cessazione.",
      ]},
      { title: "9. Disposizioni finali", paragraphs: [
        "Il proprietario può aggiornare i termini; le modifiche valgono dopo 14 giorni dalla pubblicazione.",
        "Per quanto non regolato si applica la legge polacca.",
        "Le controversie sono risolte dal tribunale competente per la sede del proprietario.",
        "Contatto: modulo disponibile nella Piattaforma.",
      ]},
    ],
    lastUpdatedLabel: "Ultimo aggiornamento",
    backLabel: "Torna alla home",
  },
  fr: {
    sections: [
      { title: "1. Informations générales", paragraphs: [
        "Ces conditions régissent l'utilisation de la plateforme Winqo pour générer des devis de fenêtres.",
        "Propriétaire : Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Pologne.",
      ]},
      { title: "2. Définitions", paragraphs: [
        "Plateforme – le système SaaS Winqo.",
        "Utilisateur – toute personne ou entité utilisant la Plateforme.",
        "Compte – compte individuel de l'Utilisateur sur la Plateforme.",
        "Abonnement – accès payant aux fonctionnalités.",
        "Devis – document généré par la Plateforme.",
      ]},
      { title: "3. Conditions d'utilisation", paragraphs: [
        "L'utilisation nécessite une inscription et l'acceptation des présentes conditions.",
        "Les données fournies doivent être exactes.",
        "Les identifiants ne doivent pas être partagés avec des tiers.",
        "L'utilisation doit respecter la loi et les bonnes pratiques.",
      ]},
      { title: "4. Forfaits et paiements", paragraphs: [
        "Plusieurs forfaits avec limites et fonctions définies sont disponibles.",
        "Les frais sont prélevés à l'avance chaque mois ou année.",
        "Les changements de forfait sont possibles à tout moment et s'appliquent à la prochaine période.",
        "Le non-paiement peut bloquer l'accès.",
        "Les paiements ne sont pas remboursables sauf obligation légale.",
      ]},
      { title: "5. Données personnelles", paragraphs: [
        "Responsable : Camillo Kamil Kwapich, ul. Swierkowa 33b, 46-100 Namyslow, Pologne.",
        "Les données sont traitées selon le RGPD pour fournir le service.",
        "L'utilisateur peut accéder, rectifier, supprimer et porter ses données.",
        "Les données ne sont pas partagées sans consentement, sauf avec les prestataires de paiement.",
      ]},
      { title: "6. Responsabilité", paragraphs: [
        "La Plateforme est fournie \"en l'état\" sans garantie de disponibilité.",
        "Le propriétaire n'est pas responsable des dommages liés à l'usage ou à l'indisponibilité.",
        "L'utilisateur est responsable du contenu des devis générés.",
        "Des maintenances peuvent avoir lieu.",
      ]},
      { title: "7. Propriété intellectuelle", paragraphs: [
        "Tous les droits sur la Plateforme, le code et la documentation appartiennent au propriétaire.",
        "L'utilisateur reçoit une licence non exclusive dans le cadre de son abonnement.",
        "Il est interdit de copier ou diffuser sans consentement.",
      ]},
      { title: "8. Résiliation", paragraphs: [
        "L'utilisateur peut annuler l'abonnement à tout moment.",
        "Le propriétaire peut résilier avec un préavis de 30 jours ou immédiatement en cas de violation.",
        "Les données peuvent être supprimées 30 jours après la résiliation.",
      ]},
      { title: "9. Dispositions finales", paragraphs: [
        "Le propriétaire peut mettre à jour les conditions; elles s'appliquent 14 jours après publication.",
        "Le droit polonais s'applique pour les points non couverts.",
        "Les litiges sont tranchés par le tribunal compétent du siège du propriétaire.",
        "Contact : formulaire disponible sur la Plateforme.",
      ]},
    ],
    lastUpdatedLabel: "Dernière mise à jour",
    backLabel: "Retour à l'accueil",
  },
  "en-us": undefined as unknown as TermsContent,
  "en-uk": undefined as unknown as TermsContent,
};

TERMS_BY_LANG["en-us"] = TERMS_BY_LANG.en;
TERMS_BY_LANG["en-uk"] = TERMS_BY_LANG.en;

export default function Terms({ params }: { params: { lang: string } }) {
  const lang = (isLang(params.lang) ? params.lang : "en") as Lang;
  const content = TERMS_BY_LANG[lang] || TERMS_BY_LANG.en;

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-purple-50 px-4 py-14">
      <div className="mx-auto max-w-4xl">
        <div className="rounded-3xl bg-gradient-to-br from-white to-blue-50 p-8 glow-card border border-blue-100">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent mb-8">
            {t(lang, "terms_title")}
          </h1>

          <div className="prose prose-blue max-w-none space-y-6 text-gray-700">
            {content.sections.map((section, idx) => (
              <section key={idx}>
                <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">{section.title}</h2>
                {section.paragraphs.map((p, i) => (
                  <p key={i} className={i === 0 ? undefined : "mt-2"}>{p}</p>
                ))}
              </section>
            ))}

            <div className="mt-12 pt-6 border-t border-gray-200 text-sm text-gray-600">
              <p>{content.lastUpdatedLabel}: {new Date().toLocaleDateString(lang === "pl" ? "pl-PL" : "en-US")}</p>
            </div>
          </div>
        </div>

        <div className="mt-6 text-center">
          <a
            href={`/${lang}`}
            className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium transition-colors"
          >
            ← {content.backLabel}
          </a>
        </div>
      </div>
    </main>
  );
}
